language: node_js
matrix:
  fast_finish: true
node_js:
- '6'
branches:
  except:
  - build
env:
  global:
  - CXX=g++-4.8
  - secure: UMe84F7f9T1pezGfYvqemKT628rSduOyMKDdhc2mGyJG7f8+2yZWLpDUdKO4fGzshC7GvJ9kPj0LtrxQ0tXZlCxoskxNf3rYhUlFv+xqowndaj4DNdKOvC0HLgHmxitWo8/vyJmM7b9EMJWY9/BGJhqy/ckc63hd5dOHHRj2pJxSbnkbjlhLebJ7+8rmSgyzxFYlW52A+4aV33Kv3F185FUVLHWMYhrlfmUg+u7VcY58jONsXRtvuNCGEbk/uI2k7C6wDh/6+rRFXXpyNzDwUvEbKCQtSJcngTC4yk979KjzZit0fwLBi5628jKg1QrDQDeF9Za13OC1jT380yv7eCBpaQoiwgcyFnLiEV4DZVw6WAp5TmtJX6uP7gM5cCuPFPy/i3rma9mHBZH+B3eOqt1IIjYf2XUnumMGgEBkpu9+Q6ROWuldx8Zfa4s0CXtOk7OzMG4HewX1WbK0+DLda4gF7oMVGPq401X4Z6UJHhDQd2V08HbzsamsQ58Q6ub7UvYssDyhq7ZPKdQhCcXo1niLsPN/REfehRvZOLD88M7FMsr1gEG0PxYp0bJxvn2fn+11B3gYIlYZf0INKB5Qkm+7Mu5va3iupex4wGNE3fapXBp3mXDJ6e/qzYhcgIlEESVg9qHATP/Vc3NZfXFq8CP309RjkAtxHu2bE/ZS4Rw=
  - secure: eeAdjR+K9YB/tCUn5P9d3CSNfnaUjgb8Rny/Jf5C7wu6NE3+J8m9tqudRleR6XWiER4JYrNuHLr3/i3x97QXR0PXQffNrl9E+y/Q9HXm/7c3U0qBUU0Fm/tfwHxKxl4aXckqqKbi4Z+XC0mnsct+PzqNhZzysLQRpECy4VfGVgid1SgdN8pmhC7/0LM5wduRRouRw600JfMvbSeIovhNlJIw93i7XnFC1E4Iy+S1yPLqNcVuZrzLtSnqJkflRLXyZwLB9wwhdSkLb78ut6w+CgORyIdeORTaEP+gP0eBQpoEM0sE13bsNGo6/g+DG+LLQsc+2NHpCQo8DVCBfAOuwwmsHXQuEqLkCJPu7+lSlkxHOXqpyE+thT6EtkOsAwqcX5Wksb0iEfCPMsh1Q13XK8TeDh7Y8e9uV2mMeBR3JiN2JUASlx16P8gtdmbKpeEdOnvnMQ6P4gph78xT5LHuGMOkYkr3DQmGZw4KC3bgxdcXkHdiPTFwIfNdSbt+EYbCFxfGGDM32trAAT6gG9pq7lRq/0IXMLq/crLZVoS6Pb67maUAZiqGgUMkU8CEIjDwp4rDQ3dcP3f5cbIDX0QXNlw4vDjK3kUL8zugq6KebEkfLPFeoE3MqF7aCSS5XuOzSl08UH5x4PFlLItIPilLDn5NFx7Q5FOTjyx1XtYadP0=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - deadsnakes
    packages:
    - g++-4.8
    - python3.5
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- curl -fsSL https://bootstrap.pypa.io/get-pip.py | python3.5 - --user
- travis_retry pip3.5 install --user transifex-client
- install -m0644 .transifexrc.tpl ~/.transifexrc
- echo "password = $TX_PASSWD" >> ~/.transifexrc
script:
- yarn test
- yarn build:browser
after_success:
- test $TRAVIS_BRANCH = "master" && yarn run deploy -- --branch=build
- test $TRAVIS_BRANCH = "prod" && yarn run deploy -- --branch=latest
