language: node_js
matrix:
  fast_finish: true
node_js:
- '8'
branches:
  except:
  - build
env:
  global:
  - CXX=g++-4.8
  - TARGETS_DEV=recette.cozy.works
  - TARGETS_BETA=betatest.cozy.works
  - MATTERMOST_CHANNEL=Plateformers-release
  # to generate secure ENV VARS : travis encrypt MY_VAR=value -r cozy/cozy-store
  # RUNDECK_TOKEN
  - secure: "Ag7L9ONuRQ77poU1hW6DBPGM+sJO4Rfc0mvg0Io3ul/X8ArJNKozsav6DBJr+7GbZk+A7snPP0U7F6QxB0ObW7Ix9mXNyCL45opqFEejsWsKb6JHoDgK79fvhQlSeEknSrnHzSUykBLSODUEr0nnDzG5F4YiVOM9v02ZhvydrjlwCYBHZrsbdOKdHgEBMEZ1sfCDs4iSrTSRxmsRp6snSpqvVHr+ir7cZq5gUbFA319huKr+hrW2r0/9oMPlce+k5wVYR7Wiq/RQ4flgqP7CpEhjH+w20fDIbZpVgAy24YkSwK0XhZeMeElwU3vD4YX1IfdQLgRCJHUwQJiUHJvKN29rStKlL2JsL/kCTvszTgSXJh76eKkxIayrCoyom2R6Ll4avG+GGZ9QyqCcpYMr+hsfXDbY3nSFT2OStIcQX59wBJkSIq0pYyZUz1V/eMXu8bfyYJTUbf2b4O6e3uNsCs6SHFmCRYovwvRT4w7KF2vIHWP9l/ZqXDVkl2pGhsgtqjmY9HZbdE1IGxjhIbBL2RJERCrOeoXKi8kbGcJyPhwyDANAxcgNWLQDfSkN3S7z1Vz+fuCuihiKljgI8MkSlPJ4t6yJqt6UXQdS85WczM/IcaWWp0jJ0o1NGIqYOAPaivnlV+JBNCH4MSlASpV3OWd5C20pqdw+SFNtsdneqeE="
  # MATTERMOST_HOOK_URL
  - secure: "w2Ib1GvqtXAffZU6ZVDwhXcZYwCIby+UZzEC42/3XGMAd8N3sUMwPdTcO4xvMRtvbfi8XwHRPbTw69A8LLJodGj3BV4KMBe+0vfsdll0VGt53yN8K4qpDK+LYc+NopVzJVXXhDxVz1FXrFwu5Ww8ecZCyQbBUURJ0CrjbVGg1Wra19Q6yyDfhh/OljY9CCSD7tZL0fskio+DaHg12zrYzWB7vx8t+QpGpR4Yd4WcepzXLjg5Vw1P1nepvnduw+dZ7gThsX55YzkGyDJgtJq7hrrupq5/aelockFmUe7nGwVJhLGjKrSwwl6dUFObAaiR+x/RcPc5B+o3cJSCdknNezwfeJQNprL7H4ej4r5i/s/fZV8vjOpmHJETJ8qcz7Mhdp0y0mG+aNEqo6y1EteDvtOwPUnIsjN+e5E1AkalnuHGAf1GvdQK3zE6vMoMe9YIU6wjB621x3N2o547rC8eI0AulGEL662mau2Zv+0yhX/fW/9snKiYAuX3KFAv9W7trxqiHvbTTbpS+o+S45GPBrvs9DM4FXWktERzX3ZlkL9NMUqoDbNKK3OmTzfOpkEodgaL0yzaMHDnvH+txQbbvEFJrxB5JWqlxGcfRNL5uRTWLTLoaz6qKImV02+ttFqLh5uWGM9FWRYWVqFfL0zAoICSJy2yx1D92uWZXMYxDTo="
  # TX_PASSWD
  - secure: UMe84F7f9T1pezGfYvqemKT628rSduOyMKDdhc2mGyJG7f8+2yZWLpDUdKO4fGzshC7GvJ9kPj0LtrxQ0tXZlCxoskxNf3rYhUlFv+xqowndaj4DNdKOvC0HLgHmxitWo8/vyJmM7b9EMJWY9/BGJhqy/ckc63hd5dOHHRj2pJxSbnkbjlhLebJ7+8rmSgyzxFYlW52A+4aV33Kv3F185FUVLHWMYhrlfmUg+u7VcY58jONsXRtvuNCGEbk/uI2k7C6wDh/6+rRFXXpyNzDwUvEbKCQtSJcngTC4yk979KjzZit0fwLBi5628jKg1QrDQDeF9Za13OC1jT380yv7eCBpaQoiwgcyFnLiEV4DZVw6WAp5TmtJX6uP7gM5cCuPFPy/i3rma9mHBZH+B3eOqt1IIjYf2XUnumMGgEBkpu9+Q6ROWuldx8Zfa4s0CXtOk7OzMG4HewX1WbK0+DLda4gF7oMVGPq401X4Z6UJHhDQd2V08HbzsamsQ58Q6ub7UvYssDyhq7ZPKdQhCcXo1niLsPN/REfehRvZOLD88M7FMsr1gEG0PxYp0bJxvn2fn+11B3gYIlYZf0INKB5Qkm+7Mu5va3iupex4wGNE3fapXBp3mXDJ6e/qzYhcgIlEESVg9qHATP/Vc3NZfXFq8CP309RjkAtxHu2bE/ZS4Rw=
  # GITHUB_TOKEN
  - secure: jYQ0y7bxmoO8eUJla36y1zrhtnxi0guSD4ufRQGnYmAlp7sWYeCBQj4ACXnIaTOwAhd2EpFUUp8BZ0z7W5sDUgOdYqAQe1eTe17kc2xJmDHMkW3INRYAW7LVgZTDmFLAmh5pXcdv0roGqB3KoU9PauhO8Q1h6IHwwbRslPngX2A2MYQLpobugmi0AxUff1C6bSP3rdO0GHbaAN6sYMtPzZRTeiRLaBCh3gbQhYVLFmfqVdYulHAS1TqaOGUpMEosfC+FIw/14b1u+pyWQHA5BSBrDDmqnHjcQZtugQNJP2Epw8UW1aVM1HwlU5fh3/Ru/LZ/+bDc/Xg26C+OKJzF5Loo8owdlFcPjh7/hnamARz8jhB2jCJzwpTtBeTkX6O9xVDoPcBnNypaf3Ck8glZ0xg9AbnpOwmy7KYbKffDe6uRq6whJEQOvgmdTYlFXWS1wY0IS2J2pPw9QaHmhM+eQNxS1mrL59CPsP9y+b58mNRPLMscE3RYn5un5xlRYQKbT1JUHh0eFmVlAciEl5U5t2FGccPwSUyPN9pM2yf/1jmyNq16sR8XCvMgzHXI2Hev8UumEq2qthQfZ6WfXQDSfJhgPCsCZq89IhxmzwOLACk7Tk/Bw4ryrSfldfGxpozuJmppQGRatPwaJToHKLg1CcoQ/6d5wxpViS68X1HrZWY=
  # REGISTRY_TOKEN
  - secure: lG8EXRnx6k/pS5ABk1UJl1743VSEU9GXmya/z0cIhgeSiQ9IWpQoS3Kdk5ZDgm35Sm/MnBvcfFPbqsWGLIXGYBEV9TW7kf7I0JL/x8doG+otau2fHT54J1yC4lzpJbxgwnmsEo6iusaiqTthrDO4BV5tboB0YarJIfZ56q/ASGB/18oTafItVC73x8iH9hiX6n1MjqFyVAfmyBoUAOKI4m83ijB+LyqbOLWpZg3LCD5LxbIRAqG/+a/AOBRl5gvH9z5+ZIJZD2JYBlkhnQL9rZ65Q2lLH5N8BbaC/85IZTEUb4zBV0qgO9suZepMM5TNmYKy7Ix70z+FgAEwGkLEEB2KbMya9ZoL+mu+ImffsSs2CIT9OJxNpT0yWwRnXUvI7VgT8bJuirMTWCVPDO5qmW7uKED0PFd7Q/7MnqWQhqoHAt4xa7lYQvKbfs8ISMbiWlLXyaqRT3hdrZnBJ89Vrotu5eu2ce5sCgS4FcKEAWZ0NwATqkJHMf23H88gD7VrIqYQpX/DM5vuw2rCAVcBcbdOI5CEyt8foF6Ib9aSNGd7whLLcTxue7x7vPj658nfzS8hiZQcBiyQvKiLy5lGfBQ7T7edilFWX91HfnO2dACWtZJfVw0DrXu8G6HKuJM77wwrMZanTXw82oWxiyCRn0EGgmYYBNFn5dj3Vzd/ZmM=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - deadsnakes
    packages:
    - g++-4.8
    - python3.5
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- if [ "$TRAVIS_SECURE_ENV_VARS" != "false" ]; then openssl aes-256-cbc -K $encrypted_e8e75da126d5_key -iv $encrypted_e8e75da126d5_iv -in deploy/id_rsa_downcloud_cozy-store.enc -out /tmp/id_rsa_downcloud_cozy-store -d; fi
- if [ "$TRAVIS_SECURE_ENV_VARS" != "false" ]; then eval "$(ssh-agent -s)"; fi
- if [ "$TRAVIS_SECURE_ENV_VARS" != "false" ]; then chmod 600 /tmp/id_rsa_downcloud_cozy-store; fi
- if [ "$TRAVIS_SECURE_ENV_VARS" != "false" ]; then ssh-add /tmp/id_rsa_downcloud_cozy-store; fi
- curl -fsSL https://bootstrap.pypa.io/get-pip.py | python3.5 - --user
- travis_retry pip3.5 install --user transifex-client==0.12.5
- install -m0644 .transifexrc.tpl ~/.transifexrc
- echo "password = $TX_PASSWD" >> ~/.transifexrc
script:
- yarn test
- yarn build
deploy:
- provider: script
  repo: cozy/cozy-store
  skip-cleanup: true
  script: yarn cozyPublish
  on:
    branch: master
- provider: script
  repo: cozy/cozy-store
  skip-cleanup: true
  script: yarn cozyPublish
  on:
    tags: true
